# --------// Pudantic models defining agents short-term mermory state // -------- #
import operator
from typing import Annotated, List, Optional
from pydantic import BaseModel, Field


# ----- Data Models ----- #
class ResearchQuery(BaseModel):
    """A single specific research task."""

    id: str
    query: str
    rationale: str


class ResearchResult(BaseModel):
    """The raw data found for a query"""

    query_id: str
    content: str
    source: str


class UserProfile(BaseModel):
    """Long-term memory of user preferences."""

    name: str = "User"
    preferences: List[str] = Field(default_factory=list)
    tone_preference: str = "neutral"


# ------ Graph State ------
class AgentState(BaseModel):
    """
    The Global state of the Agent.
    Langgraph passes this state between nodes.
    """

    # The original user request
    task: str

    # Long-term memory context loaded at start
    user_profile: UserProfile = Field(default_factory=UserProfile)

    # The plan generated by the planner
    research_plan: List[ResearchQuery] = Field(default_factory=list)

    # Aggregate the research results.
    research_results: Annotated[List[ResearchResult], operator.add] = Field(
        default_factory=list
    )

    # The draft content generated
    draft_content: str = ""

    # Feedback provided by human
    human_critique: Optional[str] = None

    # Counter for preventing infinite refinement loops
    revision_count: int = 0
